Repository aesara-devs/aeppl, pull requests merged in 2021-12, with the labels that each got.

#95 Use specialized CheckAndRaise Op in logprob graphs
  aeppl/logprob.py
  aeppl/truncation.py
  setup.py
  tests/test_logprob.py
Labels: enhancement

#97 Import `Assert` from its new module
  aeppl/printing.py
Labels: bug

#100 Rename internal value variables in factorized_joint_logprob
  aeppl/joint_logprob.py
Labels: refactoring
