Repository aesara-devs/aeppl, pull requests merged in 2021-11, with the labels that each got.

#72 Cumsum rvs
  aeppl/__init__.py
  aeppl/cumsum.py
  tests/test_cumsum.py
Labels: enhancement, graph rewriting, op-probability

#88 Fix bug in missing measurable variable warning
  aeppl/joint_logprob.py
  tests/test_cumsum.py
  tests/test_joint_logprob.py
Labels: bug

#89 Revert "Allow both edges of IntervalTransform to be None"
  aeppl/transforms.py
  tests/test_transforms.py
Labels: rv-transforms

#20 Add a Gitter chat badge to README.rst
  README.rst
Labels: documentation
