Repository aesara-devs/aeppl, pull requests merged in 2022-12, with the labels that each got.

#211 added the name of the author
  setup.py
Labels: documentation

#215 Set dtype of zeros in mixture condition
  aeppl/mixture.py
  tests/test_mixture.py
Labels: bug

#217 Change use of `TensorType.broadcastable` to `TensorType.shape`
  aeppl/logprob.py
  aeppl/mixture.py
  tests/test_logprob.py
Labels: enhancement
