Repository aesara-devs/aeppl, pull requests merged in 2022-01, with the labels that each got.

#103 Remove unnecessary `update_rv_maps` call in `mixture_replace`
  aeppl/mixture.py
Labels: refactoring

#104 Use IfElse in Mixture logprob when index is scalar
  aeppl/mixture.py
Labels: op-probability

#108 Fix scalar mixture distributions with non-scalar index case
  aeppl/mixture.py
  tests/test_mixture.py
Labels: bug

#109 Remove unnecessary assert in `naive_bcast_rv_lift`
  aeppl/opt.py
  tests/test_opt.py
Labels: bug

#110 Add Dirac-delta support
  aeppl/dists.py
  aeppl/logprob.py
  aeppl/mixture.py
  aeppl/opt.py
  tests/test_dist.py
  tests/test_logprob.py
  tests/test_mixture.py
  tests/test_opt.py
Labels: enhancement, op-probability

#112 Take the abs value of the Jacobian determinant in the default transform
  aeppl/transforms.py
Labels: bug, rv-transforms

#117 Remove Python 3.6 from the CI test matrix
  .github/workflows/test.yml
Labels: CI, testing
