Repository aesara-devs/aeppl, pull requests merged in 2022-08, with the labels that each got.

#159 Implement measurable `DimShuffle`s
  aeppl/tensor.py
  tests/test_tensor.py
Labels: enhancement, op-probability

#164 Only introduce MeasurableDimShuffles when input is a RandomVariable
  aeppl/tensor.py
  tests/test_tensor.py
Labels: bug, graph rewriting

#165 Fix the use of deprecated objects
  aeppl/logprob.py
  aeppl/printing.py
  tests/test_composite_logprob.py
Labels: enhancement, refactoring

#154 Introduce graph rewrite for mixture sub-graphs defined via `Switch`
  aeppl/mixture.py
  tests/test_mixture.py
Labels: enhancement, graph rewriting, op-probability
