Repository aesara-devs/aeppl, pull requests merged in 2022-04, with the labels that each got.

#132 Remove `ignore_logprob` checking
  aeppl/joint_logprob.py
  tests/test_joint_logprob.py
Labels: refactoring

#133 Assign IR-related rewrites to `logprob_rewrites_db`
  aeppl/cumsum.py
  aeppl/mixture.py
  aeppl/scan.py
  aeppl/truncation.py
Labels: graph rewriting, refactoring

#136 Preserve mode in MeasurableScans
  aeppl/scan.py
  tests/test_scan.py
Labels: bug

#139 Remove unused code in `invgamma_logprob`
  aeppl/logprob.py
Labels: refactoring

#140 Return updates created by `discrete_markov_chain`
  aeppl/dists.py
  tests/test_dist.py
Labels: bug, enhancement

#141 Implement `_get_measurable_outputs` for `DiscreteMarkovChainFactory`
  aeppl/dists.py
  tests/test_dist.py
Labels: bug, enhancement, op-probability

#26 Implement chained transforms
  aeppl/__init__.py
  aeppl/transforms.py
  tests/test_composite_logprob.py
  tests/test_transforms.py
Labels: enhancement, important, rv-transforms
